package com.poo.urnaeletronica.view;

import java.awt.event.ActionEvent;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jPasswordFieldCodigoAutenticar = new javax.swing.JPasswordField();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelCodigoAutenticar = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setText("Sair");
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 70, -1));

        jButtonEntrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jPasswordFieldCodigoAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificaCodigoAutenticar(evt);
            }
        });
        getContentPane().add(jPasswordFieldCodigoAutenticar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 200, 30));
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 200, 30));

        jLabelCodigoAutenticar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCodigoAutenticar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoAutenticar.setText("Senha");
        getContentPane().add(jLabelCodigoAutenticar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("Login");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabelTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("TelaLogin.png"))); // NOI18N
        getContentPane().add(jLabelTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        pack();
    }
    protected void jButtonEntrarActionPerformed(ActionEvent evt) {
    }

    private void VerificaCodigoAutenticar(java.awt.event.ActionEvent evt) {
    }

    private void VerifcaLogin(java.awt.event.ActionEvent evt) {
    }

    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelCodigoAutenticar;
    private javax.swing.JLabel jLabelTelaLogin;
    private javax.swing.JPasswordField jPasswordFieldCodigoAutenticar;
    private javax.swing.JTextField jTextFieldLogin;
}
